import type { TravelLocation, TravelPhoto } from "./types";
import { travelLocations } from "./locations";
import manifest from "./photos.manifest.json";

/**
 * Loads travel locations with their photos.
 *
 * Photos come from a cached manifest (`photos.manifest.json`) generated by
 * `npm run refresh:photos`, NOT from a live Cloudinary call. This keeps builds
 * instant and avoids hammering (and rate-limiting) the Cloudinary Admin API.
 * Run the refresh script whenever you add or change photos.
 */

interface Manifest {
  generatedAt: string | null;
  photosByLocation: Record<string, TravelPhoto[]>;
}

export function loadTravelLocations(): TravelLocation[] {
  const { photosByLocation } = manifest as Manifest;

  return travelLocations.map((meta) => ({
    ...meta,
    photos: photosByLocation[meta.id] ?? [],
  }));
}
